version: '3'
services:
  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_ADMIN_ENABLED: "true"
      INFLUXDB_DB: uptime
  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'
